print('hello world')
print(r'''//jkgakjglkajgljakjgkajljglkajgjlkarjklgjakeljglkejaklgjlkajrgjlka''')
print('hello world'.title())
print('hello world'.upper())
print('hello world'.lower())
print('helllo world '.rstrip())
print(' hello'.lstrip())
print(' hello '.strip())
print(2 * 0.1)
print('happy ' + str(30) + 'rd Birthday')
