print(0b10)
print(bin(10))
print(bin(0xE))
print(bin(0o7))
print(int(0b111))
print(hex(888))
print(oct(0b111))
print(True)
type(True)
print(type(True))
print(int(True))
print(bool(1))
print(bool(''))
print(bool('nihao'))
print(26j)
print("let's go")
print('''hello world\nhello world\nhello world''')